---
title: "pareto_stocks"
author: "Tyler Finnerty"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(readxl)
library(dplyr)
```

```{r}
tickers <- read_xlsx("data/Holdings_duplicates_comparison.xlsx")
```

```{r}
set.seed(1)
# Group the data by stock type and then sample 5 stocks from each group
selected_stocks <- tickers %>%
  group_by(ETF) %>%
  sample_n(size = 5, replace = FALSE)

set.seed(2)
selected_stocks_2 <- tickers %>%
  group_by(ETF) %>%
  sample_n(size = 5, replace = FALSE)

set.seed(3)
selected_stocks_3 <- tickers %>%
  group_by(ETF) %>%
  sample_n(size = 5, replace = FALSE)

set.seed(4)
selected_stocks_4 <- tickers %>%
  group_by(ETF) %>%
  sample_n(size = 5, replace = FALSE)

# replacing certain stocks
final_stocks <- selected_stocks
final_stocks[4, ] <- selected_stocks_2[3, ]
final_stocks[10, ] <- selected_stocks_2[9, ]
final_stocks[11, ] <- selected_stocks_3[11, ]
final_stocks[12, ] <- selected_stocks_3[12, ]
final_stocks[13, ] <- selected_stocks_3[14, ]
final_stocks[14, ] <- selected_stocks_4[13, ]
final_stocks[18, ] <- selected_stocks_2[19, ]
```

```{r}
type_ticker <- final_stocks %>% 
    select(ETF, HOLDINGS, TICKER) %>% 
    rename(type = ETF, name = HOLDINGS, ticker = TICKER)

# Manually adding market caps as of Jan 05, 2015. Millions of nominal US $
mkt_caps_2015 <- c("8440", "24680", "5630", "340950", "21390", 
                   "4080", "19120", "3250", "76510", "10080",
                   "870", "920", "2670", "1160", "3110",
                   "1690", "14920", "4590", "1020", "3240")

# Manually adding p/b ratios Dec 31 2014 or Jan 31 2015
pb_ratios_2015 <- c("8.63", "0.86", "6.21", "3.48", "0.88",
                    "3.84", "2.46", "1.92", "1.34", "1.30",
                    "1.57", "1.18", "7.92", "6.52", "6.58",
                    "0.67", "4.27", "2.54", "0.68", "3.82")

type_ticker <- type_ticker %>% 
    ungroup() %>% 
    mutate(mkt_cap_2015 = mkt_caps_2015, pb_ratio_2015 = pb_ratios_2015)
```

```{r}
type_ticker$mkt_cap_2015 <- as.numeric(type_ticker$mkt_cap_2015)
type_ticker$pb_ratio_2015 <- as.numeric(type_ticker$pb_ratio_2015)

mkt_cap <- type_ticker %>% 
    arrange(desc(mkt_cap_2015))

final_df <- mkt_cap %>% 
    mutate(size = ifelse(mkt_cap_2015 > median(mkt_cap_2015), "Large", "Small"),
           value = ifelse(pb_ratio_2015 > median(pb_ratio_2015), "Growth", "Value")) %>% 
    select(-type)

```

```{r sp500_stuff}
sp500_data <- read_csv("data/^GSPC_daily_historical_data.csv")

sp500_2015 <- sp500_data %>% 
    select(Date, 'Adj Close') %>% 
    mutate(across(-Date, ~ log(. / lag(.)))) %>% 
    rename(daily_log_return = 'Adj Close') %>% 
    filter(Date >= as.Date("2015-01-01") & Date <= as.Date("2019-12-31"))

sp500_log_return <- sapply(sp500_2015[-1], function(x) mean(x, na.rm = TRUE)) * 252

sp500_2020 <- sp500_data %>% 
    select(Date, 'Adj Close') %>% 
    mutate(across(-Date, ~ log(. / lag(.)))) %>% 
    rename(daily_log_return = 'Adj Close') %>% 
    filter(Date >= as.Date("2020-01-01"))

sp500_avg_yearly_log_return <- mean(sp500_2020$daily_log_return, na.rm = TRUE) * 252
sp500_standard_deviation <- sd(sp500_2020$daily_log_return, na.rm = TRUE) * sqrt(252)
```

```{r}
twenty_raw <- read_csv("data/20_stocks_2.csv")

twenty <- twenty_raw %>% 
    select(Date, 'Adj Close', Ticker)

twenty_final <- twenty %>% 
    pivot_wider(., names_from = Ticker, values_from = 'Adj Close') %>% 
    na.omit()

log_returns <- twenty_final %>%
    mutate(across(-Date, ~ log(. / lag(.)))) %>% 
    filter(Date >= as.Date("2015-01-01") & Date <= as.Date("2019-12-31"))

# then follow the SAT example:
## Accuracy = accuracy of picking outperformers
## fairness = inclusion of all outperformers

# Calculate the average log return for each ticker
yearly_log_returns <- sapply(log_returns[-1], function(x) mean(x, na.rm = TRUE)) * 252

# Create a new data frame to store ticker names and average log returns vertically
vertical_df <- data.frame(ticker = names(yearly_log_returns), 
                          average_log_return = yearly_log_returns) %>% 
    mutate(outperform = ifelse(average_log_return > sp500_log_return, 1, 0)) # check outperformance

final_df <- inner_join(final_df, vertical_df, by = "ticker")
```

```{r}
# accuracy <- numeric(nrow(mkt_cap))
# inclusion <- numeric(nrow(mkt_cap))
# 
# # initialize the following:
# # inclusion <- 
# # accuracy <- 
# 
# for(i in 1:nrow(mkt_cap)){
#     subset_mkt_cap <- mkt_cap[1:i, ]
#     
#     inclusion[i] <- a
#     
#     accuracy[i] <- subset_mkt_cap$outperform 
# }

# Initialize vectors to store accuracy and inclusion values
accuracy_values <- c()
inclusion_values <- c()

# Loop over each row of the data frame
for (i in 1:nrow(final_df)) {
  
  # Subset data up to the current row
  subset_data <- final_df[1:i, ]
  
  # Calculate accuracy
  accuracy <- sum(subset_data$outperform == 1) +
      (sum(final_df$outperform == 0) - sum(subset_data$outperform == 0))
  
  # Calculate inclusion
  inclusion <- sum(final_df$outperform == 1) - sum(subset_data$outperform == 1) - 
      (sum(final_df$outperform == 0) - sum(subset_data$outperform == 0))
  
  # Append accuracy and inclusion values to vectors
  accuracy_values <- c(accuracy_values, accuracy)
  inclusion_values <- c(inclusion_values, inclusion)
}

# Create a data frame to store accuracy and inclusion values
plot_data <- data.frame(Stock_Number = 1:nrow(mkt_cap),
                        Accuracy = accuracy_values,
                        Inclusion = inclusion_values)

# Plot accuracy against inclusion
ggplot(plot_data, aes(x = Accuracy, y = Inclusion)) +
  geom_point() +
  labs(x = "Accuracy", y = "Inclusion") +
  theme_minimal() 

# the plot is just a line, i think its because there isn't two distinct groups that
# we are trying to be fair to. There might be a way around this without creating groups 

```

```{r by_mkt_cap}
by_mkt_cap <- final_df %>% 
    arrange(desc(mkt_cap_2015)) %>% 
    mutate(Stock_Number = 1:nrow(final_df))

# Initialize vectors to store accuracy and inclusion values
accuracy <- numeric(nrow(by_mkt_cap))
inclusion <- numeric(nrow(by_mkt_cap))

# Initialize variables to store counts of outperform by value
outperform_growth <- sum(by_mkt_cap$outperform[by_mkt_cap$value == "Growth"])
outperform_value <- sum(by_mkt_cap$outperform[by_mkt_cap$value == "Value"])

# Iterate through each subset of individuals with decreasing SAT scores
for (i in 1:nrow(by_mkt_cap)) {
  subset_data <- by_mkt_cap[1:i, ]
  
  # Calculate accuracy: sum of 1s in outperform set and 0s in underperform set
    accuracy[i] <- sum(subset_data$outperform == 1) + 
        (sum(by_mkt_cap$outperform == 0) - sum(subset_data$outperform == 0))
  
  # Calculate inclusion: 
    inclusion[i] <- sum(subset_data$outperform[subset_data$value == "Value"] == 1) -
        sum(subset_data$outperform[subset_data$value == "Growth"] == 1)
}


pareto_data <- data.frame(accuracy = accuracy, inclusion = inclusion)


# Create a data frame to store accuracy and inclusion values
plot_data <- data.frame(Stock_Number = 1:nrow(final_df),
                        Accuracy = accuracy,
                        Inclusion = inclusion)

# Plot accuracy against inclusion
ggplot(plot_data, aes(x = Accuracy, y = Inclusion)) +
  geom_point(size = 5) +
  labs(x = "Accuracy", y = "Inclusion") +
  theme_minimal() 

joined_mkt_cap <- inner_join(by_mkt_cap, plot_data, by = "Stock_Number") %>% 
    select(-Stock_Number)

example_table_1 <- joined_mkt_cap %>% 
    select(-c("pb_ratio_2015","size"))

```

```{r portfolio_test_1}
portfolio_1_tickers <- example_table_1 %>% 
    slice(1:14) %>% 
    select(ticker)

portfolio_1_tickers$ticker

portfolio_test_1 <- twenty_final %>% 
    select(Date, portfolio_1_tickers$ticker) %>% 
    filter(Date >= as.Date("2020-01-01"))

portfolio_test_1 <- portfolio_test_1 %>%
  mutate(across(all_of(portfolio_1_tickers$ticker), 
                ~ log(. / lag(.)), 
                .names = "{col}_log_return"))

log_return_cols <- paste0(portfolio_1_tickers$ticker, "_log_return")

# Calculate averages and standard deviations for each stock
port1_averages <- colMeans(select(portfolio_test_1, 
                                  all_of(log_return_cols)),
                           na.rm = TRUE) * 252
port1_standard_deviations <- apply(select(portfolio_test_1,
                                          all_of(log_return_cols)),
                                   2,
                                   sd,
                                   na.rm = TRUE) * sqrt(252)

# Create a new data frame with ticker, average, and standard deviation
portfolio_1_mean_sd <- data.frame(
  ticker = names(port1_averages),
  avg_yearly_log_return = port1_averages,
  yearly_sd = port1_standard_deviations
)

avg_portfolio_1_log_return <- mean(portfolio_1_mean_sd$avg_yearly_log_return)
avg_portfolio_1_sd <- mean(portfolio_1_mean_sd$yearly_sd)
```


```{r by_pb_ratio}
by_pb_ratio <- final_df 

by_pb_ratio <- by_pb_ratio %>% 
    arrange((pb_ratio_2015)) %>% 
    mutate(Stock_Number = 1:nrow(final_df))


# Initialize vectors to store accuracy and inclusion values
accuracy_2 <- numeric(nrow(by_pb_ratio))
inclusion_2 <- numeric(nrow(by_pb_ratio))

# Initialize variables to store counts of successes by race
outperform_large <- sum(by_pb_ratio$outperform[by_pb_ratio$size == "Large"])
outperform_small <- sum(by_pb_ratio$outperform[by_pb_ratio$size == "Small"])

# Iterate through each subset of individuals with decreasing SAT scores
for (i in 1:nrow(by_pb_ratio)) {
  subset_data <- by_pb_ratio[1:i, ]
  
  # Calculate accuracy: sum of 1s in outperform set and 0s in underperform set
    accuracy[i] <- sum(subset_data$outperform == 1) + 
        (sum(by_pb_ratio$outperform == 0) - sum(subset_data$outperform == 0))
  
  # Calculate inclusion: difference of correctly included small and large stocks
    inclusion[i] <- sum(subset_data$outperform[subset_data$size == "Small"] == 1) -
        sum(subset_data$outperform[subset_data$size == "Large"] == 1)
}


pareto_data_2 <- data.frame(accuracy = accuracy, inclusion = inclusion)


# Create a data frame to store accuracy and inclusion values
plot_data_2 <- data.frame(Stock_Number = 1:nrow(final_df),
                        Accuracy = accuracy,
                        Inclusion = inclusion)

# Plot accuracy against inclusion
ggplot(plot_data_2, aes(x = Accuracy, y = Inclusion)) +
  geom_point(size = 5) +
  labs(x = "Accuracy", y = "Inclusion") +
  theme_minimal() 

joined_pb_ratio <- inner_join(by_pb_ratio, plot_data_2, by = "Stock_Number") %>% 
    select(-Stock_Number)

example_table_2 <- joined_pb_ratio %>% 
    select(-c("mkt_cap_2015", "value"))
```

```{r portfolio_test_2}
portfolio_2_tickers <- example_table_2 %>% 
    slice(1:18) %>% 
    select(ticker)

portfolio_2_tickers$ticker

portfolio_test_2 <- twenty_final %>% 
    select(Date, portfolio_2_tickers$ticker) %>% 
    filter(Date >= as.Date("2020-01-01"))

portfolio_test_2 <- portfolio_test_2 %>%
  mutate(across(all_of(portfolio_2_tickers$ticker), 
                ~ log(. / lag(.)), 
                .names = "{col}_log_return"))

log_return_cols_2 <- paste0(portfolio_2_tickers$ticker, "_log_return")

# Calculate averages and standard deviations for each stock
port2_averages <- colMeans(select(portfolio_test_2, 
                                  all_of(log_return_cols_2)),
                           na.rm = TRUE) * 252
port2_standard_deviations <- apply(select(portfolio_test_2,
                                          all_of(log_return_cols_2)),
                                   2,
                                   sd,
                                   na.rm = TRUE) * sqrt(252)

# Create a new data frame with ticker, average, and standard deviation
portfolio_2_mean_sd <- data.frame(
  ticker = names(port2_averages),
  avg_yearly_log_return = port2_averages,
  yearly_sd = port2_standard_deviations
)

avg_portfolio_2_log_return <- mean(portfolio_2_mean_sd$avg_yearly_log_return)
avg_portfolio_2_sd <- mean(portfolio_2_mean_sd$yearly_sd)
```


```{r testing_error_unfairness}
by_mkt_cap <- final_df %>% 
    arrange(desc(mkt_cap_2015)) %>% 
    mutate(Stock_Number = 1:nrow(final_df))

# Initialize vectors to store error and unfairness values
error <- numeric(nrow(by_mkt_cap))
unfairness <- numeric(nrow(by_mkt_cap))

# Initialize variables to store counts of outperform by value
outperform_growth <- sum(by_mkt_cap$outperform[by_mkt_cap$value == "Growth"])
outperform_value <- sum(by_mkt_cap$outperform[by_mkt_cap$value == "Value"])

# Iterate through each subset of individuals with decreasing SAT scores
for (i in 1:nrow(by_mkt_cap)) {
  subset_data <- by_mkt_cap[1:i, ]
  
  # Calculate accuracy: sum of 1s in outperform set and 0s in underperform set
    error[i] <- sum(subset_data$outperform == 0) + 
        (sum(by_mkt_cap$outperform == 1) - sum(subset_data$outperform == 1))
  
  # Calculate inclusion: 
    unfairness[i] <- (sum(by_mkt_cap$outperform[by_mkt_cap$value == "Value"] == 1) - 
                         sum(subset_data$outperform[subset_data$value == "Value"] == 1)) - 
        (sum(by_mkt_cap$outperform[by_mkt_cap$value == "Growth"] == 1)-
             sum(subset_data$outperform[subset_data$value == "Growth"] == 1))
}


pareto_data <- data.frame(error = error, unfairness = unfairness)


# Create a data frame to store accuracy and inclusion values
plot_data <- data.frame(Stock_Number = 1:nrow(final_df),
                        Error = error,
                        Unfairness = unfairness)

# Plot accuracy against inclusion
ggplot(plot_data, aes(x = Error, y = Unfairness)) +
  geom_point(size = 5) +
  labs(x = "Error", y = "Unfairness") +
  theme_minimal() 

joined_mkt_cap <- inner_join(by_mkt_cap, plot_data, by = "Stock_Number") %>% 
    select(-Stock_Number)

example_table_1 <- joined_mkt_cap %>% 
    select(-c("pb_ratio_2015","size"))

```

